linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - funlen
    - golint
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen

    # Only for digital ocean
    - gomoddirectives
    - gomodguard
    - musttag
