parameters: {}
environment: {}
packages:
  - name: core
    shared: false
    environment:
      OPENAI_API_TOKEN: "${OPENAI_API_TOKEN}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    parameters: {}
    annotations: {}
    functions:
      - name: bot
        binary: false
        main: ""
        runtime: "go:1.20"
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
